---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scheduler.name" . }}
  labels:
    {{- include "scheduler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "scheduler.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scheduler.name" . }}-console
  labels:
    {{- include "scheduler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.console.type }}
  ports:
    - port: {{ .Values.console.port }}
      targetPort: {{ .Values.console.port }}
      protocol: TCP
      name: http-console
  selector:
    {{- include "scheduler.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: redis://{.spec.clusterIP}:{.spec.ports[?(.name=="redis")].port}
  name: {{ .Values.redis.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: redis
    port: {{ .Values.redis.port }}
    protocol: TCP
    targetPort: 6379
  selector:
    name: {{ .Values.redis.name }}
